"""Add image_path to Gift model

Revision ID: ae86cd1821ac
Revises: ea3f66512288
Create Date: 2024-11-01 13:15:37.184712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae86cd1821ac'
down_revision = 'ea3f66512288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
